3dresample -master //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/pb02.8012.r01.volreg+tlrc.BRIK -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_Left_Putamen+tlrc -inset //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/resources/seed_ROIs/BGHAT_Left_Putamen.nii -overwrite
3dcalc -a //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_Left_Putamen+tlrc -b //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/full_mask.8012+tlrc.BRIK -expr 'a*b' -nscale -overwrite -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_Left_Putamen+tlrc
3dmaskave -mask //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_Left_Putamen+tlrc -quiet //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/pb02.8012.r01.volreg+tlrc.BRIK > //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/timecourses_test/SUB_8012_ROI_BGHAT_Left_Putamen_timecourse.txt
3dresample -master //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/pb02.8012.r01.volreg+tlrc.BRIK -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_RIGHT_Putamen+tlrc -inset //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/resources/seed_ROIs/BGHAT_RIGHT_Putamen.nii -overwrite
3dcalc -a //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_RIGHT_Putamen+tlrc -b //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/full_mask.8012+tlrc.BRIK -expr 'a*b' -nscale -overwrite -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_RIGHT_Putamen+tlrc
3dmaskave -mask //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/subject_rois_test/SUB_8012_ROI_BGHAT_RIGHT_Putamen+tlrc -quiet //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/pb02.8012.r01.volreg+tlrc.BRIK > //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.proband/8012.results/timecourses_test/SUB_8012_ROI_BGHAT_RIGHT_Putamen_timecourse.txt
3dresample -master //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/pb02.8000.r01.volreg+tlrc.BRIK -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_Left_Putamen+tlrc -inset //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/resources/seed_ROIs/BGHAT_Left_Putamen.nii -overwrite
3dcalc -a //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_Left_Putamen+tlrc -b //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/full_mask.8000+tlrc.BRIK -expr 'a*b' -nscale -overwrite -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_Left_Putamen+tlrc
3dmaskave -mask //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_Left_Putamen+tlrc -quiet //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/pb02.8000.r01.volreg+tlrc.BRIK > //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/timecourses_test/SUB_8000_ROI_BGHAT_Left_Putamen_timecourse.txt
3dresample -master //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/pb02.8000.r01.volreg+tlrc.BRIK -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_RIGHT_Putamen+tlrc -inset //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/resources/seed_ROIs/BGHAT_RIGHT_Putamen.nii -overwrite
3dcalc -a //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_RIGHT_Putamen+tlrc -b //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/full_mask.8000+tlrc.BRIK -expr 'a*b' -nscale -overwrite -prefix //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_RIGHT_Putamen+tlrc
3dmaskave -mask //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/subject_rois_test/SUB_8000_ROI_BGHAT_RIGHT_Putamen+tlrc -quiet //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/pb02.8000.r01.volreg+tlrc.BRIK > //kumc.edu/data/Research/Hoglund/Mosconi_M/AutismMotor/DAL/MRIData/GIMME_Analysis/data/Pulse60/group.control/8000.results/timecourses_test/SUB_8000_ROI_BGHAT_RIGHT_Putamen_timecourse.txt
